music-server: http://music.dc01.tramhammer.org:4533 # Include port number if needed
music-server-username: admin # Username for the music server
music-server-password: password # Password for the music server
music-server-ssl: false # Set to true if the music server uses SSL
discord-client-id: 123456789012345678 # Your Discord application client ID