serverurl: http://music.dc01.tramhammer.org:4533 # Include port number if needed
serverusername: admin # Username for the music server
serverpassword: password # Password for the music server
serverssl: false # Set to true if the music server uses SSL
appid: 1377436019292504146 # Your Discord application client ID